export const siteConfig = {
  siteName: "Favorite Places Demo",
  ownerName: "Example Curator",
  siteDescription: "A tiny demo of saved places organized into shareable guides.",
  defaultSeoImage: null,
  favicon: null,
  logo: null,
  navLinks: [
    { label: "Places", href: "/" },
    { label: "About", href: "https://github.com/508-dev/favorite-places" },
  ],
  mapProvider: "auto",
  home: {
    eyebrow: "Favorite Places",
    title: "Example city guides",
    intro: "A minimal sample site pack with enough data to test search, maps, tags, top picks, and guide pages.",
    highlightsHeading: "About these guides",
    highlights: [
      "This demo uses committed raw snapshots, so it works without Google Maps scraping or API keys.",
      "Replace `site.example/` with your own `site/` pack when you are ready to publish.",
    ],
    guidesEyebrow: "Demo guides",
    guidesHeading: "Browse the sample set",
    guidesLinkText: "View the template repo",
    searchPlaceholder: "Search seafood, sunrise, markets, coffee",
    showHeroStats: true,
    showMap: true,
  },
  guide: {
    fallbackDescription: "Saved places for this city.",
    sidebarContent: ["Guide aside content can come from config or `site/content/templates/`."],
    topPicksEyebrow: "Favorites",
    topPicksHeading: "Top suggestions",
    bestHitsEyebrow: "Crowd signal",
    bestHitsHeading: "Best hits",
    browseEyebrow: "Browse",
    placesHeading: "Places",
  },
  guideCard: {
    showDescription: true,
    showTags: true,
    maxTags: 4,
    showPlaceCount: true,
  },
  placeCard: {
    showPhoto: true,
    showRating: true,
    showReviewCount: true,
    showAddress: true,
    topPickLabel: "Top pick",
  },
};
